thinkful-ei-dragonfly/stay-informed-client

- package-lock.json
- src/components/RegistrationForm/RegistrationForm.css
- src/components/RegistrationForm/RegistrationForm.js
- src/contexts/UserContext.js
- src/routes/RegistrationRoute/RegistrationRoute.js
- src/routes/Search/Search.css
- src/routes/Search/Search.js
- src/routes/UserRoute/UserRoute.js
Adds address to login, registration, and main page.  Also stores address in context.
> adding address and forms

- public/index.html
- src/contexts/UserContext.js
- src/routes/Search/Search.js
- src/services/representatives-service.js
1. Renamed app to Stay Informed
2. Create Reps Service object to run API request
3. Connected the service to the Search form
4. Get value of address, send it to service and make a request
5. Add state and district values to context for now
6. If user already exists, set placeholder to address saved in database
> Search form api call

- src/components/App/App.js
- src/components/Dashboard/Dashboard.js
Started empty shell of Dashboard component. Need to import Rob's rep list
Created route for /search and /dashboard.
After login we need to redirect to dashboard
and registration route to <Link to /search
> Lucas react update routes

- src/components/RegistrationForm/RegistrationForm.css
- src/components/RegistrationForm/RegistrationForm.js
> added link to search from registration

- src/components/Dashboard/Dashboard.js
- src/contexts/UserContext.js
Updating context, setting user context on Dashboard componentdidmount
> update context to handle request

- src/components/App/App.js
- src/routes/LoginRoute/LoginRoute.js
- src/routes/Search/Search.js
added functionality to the search button to redirect to /dashboard
> redirect from search and login to /dashboard instead of /

- src/components/App/App.js
Changed publicOnlyRoute to Route for search route
> removed PublicOnlyRoute from /search route

- src/components/AllOtherRoute/AllOtherRoute.js
- src/components/App/App.js
- src/components/PublicOnlyRoute/PublicOnlyRoute.js
- src/routes/Search/Search.js
fixed search redirect and added allotherroute.
Root goes to /dashboard
> fixed search redirect and added allotherroute.

- src/components/Dashboard/Dashboard.js
- src/components/TotalContributions/TotalContributions.js
This is just three headers with a label and the dollar amounts.  Just so you can use it in the main route and get all the data flow correct.
> added very basic total contributions component

- src/components/TotalContributions/TotalContributions.js
- src/routes/RepresentativeRoute/RepresentativeRoute.js
1. imported Dustin's component
2. Added conditionals for the props
3. created variables for topIndustries & topContributors (Rob you can pull this down from development after it's merged to test with your components)
> Deployment day

- package-lock.json
- package.json
- src/components/Dashboard/Dashboard.js
- src/components/TotalContributions/ContribsChart.js
- src/components/TotalContributions/TotalContributions.js
Added a google chart to display total contributions
> created google react chart

- src/components/Header/Header.js
- new search address link to nav dashboard
> new search nav link on dashboard

- src/components/RepresentativeList/RepresentativeList.js
Missing congressman flashy gif
> Exp missing gif

- src/components/App/App.js
- src/components/Dashboard/Dashboard.js
- src/components/VoterRegistration/VoterRegistration.css
- src/components/VoterRegistration/VoterRegistration.js
- src/config.js
- src/routes/RepresentativeRoute/RepresentativeRoute.js
- src/routes/VoterRegistrationRoute/VoterRegistrationRoute.js
- iframe from rockthevote
- a dashboard link links back to dashboard for user to take to get back
- a register to vote link is now included on the dashboard that takes you to the voter registration route
> Added a voter registration component and a voter registration route

- src/components/App/App.js
- src/components/App/App.test.js
- src/components/Dashboard/Dashboard.spec.js
- src/setupTests.js
- template smoke tests (App and Dashboard), note BrowserRouter in App
- includes testing development module dependencies
> added functional dashboard/app smoke t, test modules

- package-lock.json
- package.json
- src/components/App/App.test.js
- src/components/FinancialContributions/FinancialContributions.test.js
- src/components/VoterRegistration/VoterRegistration.test.js
- src/routes/LoginRoute/LoginRoute.test.js
- src/routes/NotFoundRoute/NotFoundRoute.test.js
- src/routes/RegistrationRoute/RegistrationRoute.test.js
- src/routes/RepresentativeRoute/RepresentativeRoute.js
- src/routes/RepresentativeRoute/RepresentativeRoute.test.js
- src/routes/Search/Search.test.js
- src/routes/UserRoute/UserRoute.js
- src/routes/VoterRegistrationRoute/VoterRegistrationRoute.test.js
- ignore console warning from FinancialContributions. Custom react-chart-js2 module quirk. It passes and will still deploy. 
- skipped RepRouteTest due to enzyme context shortcomings. confirmed via Wenc.
> Rob's passing route & FinancialContributions smoke tests

- src/components/App/App.js
- src/components/Dashboard/Dashboard.js
- src/components/ErrorDisplay/ErrorDisplay.js
- src/components/Header/Header.js
- src/components/LoginForm/LoginForm.js
- src/components/RegistrationForm/RegistrationForm.js
- src/components/RepresentativeList/RepresentativeList.js
- src/components/Spinner/Spinner.js
- src/components/TotalContributions/TotalContributions.js
- src/routes/LoginRoute/LoginRoute.js
- src/routes/RepresentativeRoute/RepresentativeRoute.js
- src/routes/Search/Search.js
- src/routes/UserRoute/UserRoute.js
- Took a lot of file sifting here. I think I looked at every file but if you happen to see something down the line that I missed def feel free to change it.
- Most notable changes were the consolidation of the htmlFor and name label and input attributes
> added semantic html and aria form recognition

- src/routes/Search/Search.js
- src/routes/Search/Search.scss
Changed state input to a dropdown of abbreviated states
> Searchfixed

- src/components/RegistrationForm/RegistrationForm.js
- src/config.js
- src/routes/Search/Search.js
Adds 50 states as select options, remove the arrows in input type=number
> Registration validation

- src/components/App/App.js
- src/components/Footer/Footer.js
- src/components/Footer/Footer.scss
It's a little ugly but I wanted to at least get it in here by the end of the day to get some group input on what to put in the footer and layout. etc.
> added a footer, but it could use work

- src/components/Dashboard/Dashboard.scss
- src/components/NewsList/NewsList.js
Let me know if you want the wording to be different, or anything to change and I can update it
> subtitle added to news

- src/components/FinancialContributions/FinancialContributions.js
- src/components/TotalContributions/ContribsChart.js
- src/routes/RepresentativeRoute/RepresentativeRoute.js
- src/routes/RepresentativeRoute/RepresentativeRoute.scss
- Strengthened copy and descriptors for financial chart summaries and titles
- feel more than free to suggest adjusted wording or ideas, this is a very detail oriented and particular topic
> added chart takeaways, strengthened descriptors to Representative page

- src/components/NewsList/NewsList.js
- src/config.js
- src/index.scss
- src/routes/LandingPage/LandingPage.js
- src/routes/LandingPage/LandingPage.scss
- src/routes/RegistrationRoute/RegistrationRoute.scss
- src/routes/Search/Search.scss
Added a bunch of small mobile updates.  Font sizes, button sizes, shrunk some margins on mobile.  check um out and let me know what you think
> Mobile updates

- src/config.js
- src/routes/LandingPage/LandingPage.js
- src/routes/LandingPage/LandingPage.scss
Let me know what you think, tear it apart as much as you want.  I just thought that our three sections were repetitive so I tried to DRY it up.
> Landing copy updates

- src/components/TextContributions/TextContributions.js
- src/routes/RepresentativeRoute/RepresentativeRoute.scss
Changed the number formats, flex properties and number of items displayed on the mobile finances.  Also displaying the descriptions now with but a smaller font size on mobile.
> Rep mobile

- src/routes/RepresentativeRoute/RepresentativeRoute.js
- src/routes/RepresentativeRoute/RepresentativeRoute.scss
Don't know how I broke the other one but this is working now.  Good catch Rob
> fixed charts on mobile and added side by side social icons

- src/components/Dashboard/Dashboard.js
- src/contexts/UserContext.js
- src/routes/RepresentativeRoute/RepresentativeRoute.js
one liner in context to scroll to top of page (page has been loading towards the middle in mobile view)
> fixed mid page componentDidMount

- LICENSE.txt
- package.json
- src/components/TextContributions/TextContributions.js
- added MIT license to root
- added MIT license to package.json
- returned empty strings in arrow functions to fix empty return console warnings
> Adding MIT license

- package.json
- src/routes/Search/Search.js
Just needed to add a className to get the alerts the right color
> add className to search form

- package.json
- src/components/ErrorDisplay/ErrorDisplay.js
- src/routes/Search/Search.js
- src/routes/UserRoute/UserRoute.js
Fixed bug where updating an address failed on unfound district, not clicking the try again button, and navigating elsewhere froze up our entire application
> Update unfound bug
